/**
 * Lightweight JSX-to-HTML converter for streaming preview.
 * Converts React JSX to browser-renderable HTML so we can show a live
 * preview in an iframe while the variant is still generating.
 *
 * Designed for STREAMING partial code: the input is an incomplete React
 * component that's still being generated by Claude.
 */

/**
 * Extract the JSX return body from a streaming partial React component.
 * Works with incomplete code that's still being generated.
 */
function extractReturnBody(jsx: string): string {
  // Strategy 1: Find "return (" and take everything after the paren
  const returnParenIdx = jsx.search(/return\s*\(/);
  if (returnParenIdx !== -1) {
    const afterReturn = jsx.slice(returnParenIdx);
    const parenIdx = afterReturn.indexOf("(");
    if (parenIdx !== -1) {
      const body = afterReturn.slice(parenIdx + 1).trim();
      return body;
    }
  }

  // Strategy 2: Find "return <" (no parens)
  const returnTagIdx = jsx.search(/return\s+</);
  if (returnTagIdx !== -1) {
    const afterReturn = jsx.slice(returnTagIdx);
    const tagIdx = afterReturn.indexOf("<");
    if (tagIdx !== -1) {
      return afterReturn.slice(tagIdx).trim();
    }
  }

  // Strategy 3: Find first JSX element after stripping JS lines
  const lines = jsx.split("\n");
  const jsxLines: string[] = [];
  let foundJsx = false;

  for (const line of lines) {
    if (!foundJsx) {
      if (line.trim().startsWith("<")) {
        foundJsx = true;
        jsxLines.push(line);
      }
    } else {
      jsxLines.push(line);
    }
  }

  if (jsxLines.length > 0) {
    return jsxLines.join("\n");
  }

  return "";
}

/**
 * Convert a camelCase CSS property to kebab-case.
 */
function camelToKebab(str: string): string {
  return str.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
}

/**
 * Convert a JSX style object to an inline CSS string.
 */
function convertStyleObject(styleMatch: string): string {
  const innerMatch = styleMatch.match(/\{\{\s*([\s\S]*?)\s*\}\}/);
  if (!innerMatch) return "";

  const inner = innerMatch[1];
  const declarations: string[] = [];

  const pairRegex = /(\w+)\s*:\s*(?:"([^"]*)"|'([^']*)'|`([^`]*)`|([^,}]+))/g;
  let match;

  while ((match = pairRegex.exec(inner)) !== null) {
    const prop = camelToKebab(match[1]);
    const value = (match[2] ?? match[3] ?? match[4] ?? match[5] ?? "").trim();
    if (prop && value) {
      const needsPx = /^-?\d+(\.\d+)?$/.test(value) &&
        !["opacity", "flex", "order", "z-index", "font-weight", "line-height"].some(p => prop.includes(p));
      declarations.push(`${prop}: ${value}${needsPx ? "px" : ""}`);
    }
  }

  if (declarations.length === 0) return "";
  return `style="${declarations.join("; ")}"`;
}

/**
 * Trim HTML to the last complete top-level element.
 * Prevents rendering half-open tags that break the layout.
 */
function trimToLastCompleteElement(html: string): string {
  if (!html.trim()) return "";

  let depth = 0;
  let lastSafeEnd = 0;
  let i = 0;

  while (i < html.length) {
    if (html[i] === "<") {
      if (html[i + 1] === "/") {
        const closeEnd = html.indexOf(">", i);
        if (closeEnd !== -1) {
          depth--;
          if (depth <= 0) {
            lastSafeEnd = closeEnd + 1;
            depth = 0;
          }
          i = closeEnd + 1;
          continue;
        }
      } else if (html[i + 1] !== "!" && html[i + 1] !== " ") {
        const tagEnd = html.indexOf(">", i);
        if (tagEnd !== -1) {
          if (html[tagEnd - 1] === "/") {
            if (depth === 0) {
              lastSafeEnd = tagEnd + 1;
            }
          } else {
            depth++;
          }
          i = tagEnd + 1;
          continue;
        }
      }
    }
    i++;
  }

  if (lastSafeEnd > 0) {
    return html.slice(0, lastSafeEnd);
  }

  return html;
}

/**
 * Validate that converted HTML looks reasonable.
 * Returns empty string if it looks like broken/raw code.
 */
function qualityGate(html: string): string {
  const trimmed = html.trim();
  if (trimmed.length < 10) return "";
  if (!/<[a-zA-Z]/.test(trimmed)) return "";

  // Reject if it looks like raw JavaScript
  const jsPatterns = /^(import |const |let |var |function |module\.|require\()/m;
  if (jsPatterns.test(trimmed)) return "";

  return trimmed;
}

/**
 * Convert JSX string to HTML that can be rendered in a browser with Tailwind.
 */
export function jsxToHtml(jsx: string): string {
  if (!jsx.trim()) return "";

  let html = extractReturnBody(jsx);
  if (!html) return "";

  // Convert style objects BEFORE removing other expressions
  html = html.replace(/\bstyle=\{\{[\s\S]*?\}\}/g, (match) => convertStyleObject(match));

  // Replace JSX attributes with HTML equivalents
  html = html.replace(/\bclassName=/g, "class=");
  html = html.replace(/\bhtmlFor=/g, "for=");

  // Remove JSX comments
  html = html.replace(/\{\/\*[\s\S]*?\*\/\}/g, "");

  // Remove event handlers
  html = html.replace(/\bon[A-Z]\w*=\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*\}/g, "");

  // Remove React-specific props
  html = html.replace(/\bkey=\{[^}]*\}/g, "");
  html = html.replace(/\bkey="[^"]*"/g, "");
  html = html.replace(/\bref=\{[^}]*\}/g, "");
  html = html.replace(/\bdangerously\w+=\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*\}/g, "");

  // Convert string expressions to plain text
  html = html.replace(/\{"([^"]*)"\}/g, "$1");
  html = html.replace(/\{'([^']*)'\}/g, "$1");
  html = html.replace(/\{`([^`]*)`\}/g, "$1");

  // Remove remaining JSX expressions
  html = html.replace(/\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*\}/g, "");

  // Convert JSX self-closing tags to HTML (for non-void elements)
  const voidElements = /^(area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr)$/i;
  html = html.replace(/<(\w+)(\s[^>]*?)?\s*\/>/g, (match, tag, attrs) => {
    if (voidElements.test(tag)) return match;
    return `<${tag}${attrs || ""}></${tag}>`;
  });

  // Replace data-generate-image with placeholder SVG
  html = html.replace(
    /<img([^>]*?)data-generate-image="[^"]*"([^>]*?)(?:\/?>)/g,
    '<img$1$2 src="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'400\' height=\'300\'%3E%3Crect fill=\'%23e5e7eb\' width=\'400\' height=\'300\'/%3E%3C/svg%3E" />'
  );

  // Strip text content that looks like code fragments
  // These appear when JSX expressions are only partially stripped
  html = html.replace(/\b(const|let|var|function|return|export|import)\b[^<]*/g, "");
  html = html.replace(/=>\s*\{?/g, "");
  html = html.replace(/&&|\|\||\?\?/g, "");
  html = html.replace(/\btrue\b|\bfalse\b|\bnull\b|\bundefined\b/g, "");
  html = html.replace(/[{};]\s*(?=<|$)/gm, "");
  // Strip .map() / .filter() / .slice() fragments
  html = html.replace(/\.\s*(?:map|filter|slice|reduce|forEach|find)\s*\([^)]*\)\s*(?:\()?/g, "");
  // Strip array/spread patterns like [...] or [
  html = html.replace(/\[\s*\.{3}[^\]]*\]/g, "");
  html = html.replace(/\[\s*\.\.\./g, "");

  // Clean up whitespace
  html = html.replace(/\s{2,}/g, " ");
  html = html.replace(/>\s+</g, "><");

  // Trim to last complete element
  html = trimToLastCompleteElement(html);

  // Quality gate
  return qualityGate(html);
}
