/**
 * Shared helpers for rendering React component previews in sandboxed iframes.
 * Used by VariantCard, ResponsivePreview, and ComparisonView.
 */

import { getIconPacks, type IconPack } from "@/lib/icons/registry";
import { buildFontTags } from "@/lib/explore/font-loader";
import type { ExtractedTokens, FontDeclaration, UploadedFont } from "@/lib/types";

const PLACEHOLDER_SVG =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='400' viewBox='0 0 800 400'%3E%3Crect fill='%23e5e7eb' width='800' height='400'/%3E%3Ctext x='400' y='200' text-anchor='middle' dy='.3em' fill='%239ca3af' font-family='system-ui' font-size='14'%3EImage placeholder%3C/text%3E%3C/svg%3E";

/**
 * Replace relative src paths (e.g. /marketing/hero.png) with a grey placeholder.
 * Prevents broken image icons in previews when AI generates fake paths.
 */
export function sanitizeRelativeSrc(code: string): string {
  return code.replace(/\bsrc=["'](\/[^"'\s>]+)["']/g, `src="${PLACEHOLDER_SVG}"`);
}

export function extractComponentName(code: string): string {
  const defaultExport = code.match(/export\s+default\s+function\s+(\w+)/);
  if (defaultExport) return defaultExport[1];

  const preferred = ["Demo", "App", "Page", "Variant"];
  for (const name of preferred) {
    if (code.includes(`function ${name}`)) return name;
  }

  const lastFn = [...code.matchAll(/function\s+(\w+)/g)].pop();
  return lastFn?.[1] ?? "App";
}

/**
 * Build CDN script tags and require() mappings for selected icon packs.
 */
function buildIconCdnScripts(iconPackIds?: string[]): { scriptTags: string; requireMappings: string } {
  if (!iconPackIds?.length) {
    return { scriptTags: "", requireMappings: "" };
  }

  const packs = getIconPacks(iconPackIds);
  const cdnPacks = packs.filter((p): p is IconPack & { cdnUrl: string; cdnGlobalName: string } =>
    p.cdnUrl !== null && p.cdnGlobalName !== null
  );

  const scriptTags = cdnPacks
    .map((p) => `<script src="${p.cdnUrl}"></${"script"}>`)
    .join("\n");

  // Build require() mappings.
  //
  // Both npmPackage and cdnGlobalName are embedded inside a JavaScript string
  // that runs in the iframe. Registry values are static today, but defence in
  // depth: JSON.stringify the npm name so any future entry with quotes or
  // backslashes can't break out of the comparison, and read the CDN global
  // via bracket notation so an oddly-named global (e.g. containing hyphens)
  // still resolves correctly.
  const mappings = packs.map((p) => {
    const pkgLit = JSON.stringify(p.npmPackage);
    if (p.cdnUrl && p.cdnGlobalName) {
      const globalLit = JSON.stringify(p.cdnGlobalName);
      return `n===${pkgLit}?window[${globalLit}]||_lucideShim`;
    }
    return `n===${pkgLit}?_lucideShim`;
  });

  return {
    scriptTags,
    requireMappings: mappings.length > 0 ? mappings.join(":") + ":" : "",
  };
}

/**
 * Build a :root { } CSS block from extraction data so preview iframes
 * can resolve var(--token-name) references generated by the AI.
 */
export function buildCssTokenBlock(
  cssVariables?: Record<string, string>,
  tokens?: ExtractedTokens,
): string {
  try {
    const vars = new Map<string, string>();

    // Valid CSS custom property names: only letters, numbers, hyphens, underscores after --
    const validNameRe = /^--[a-zA-Z0-9_-]+$/;
    // Reject characters that would break the enclosing <style> block or the
    // inner `:root { ... }` declaration. Semicolons are the silent killer —
    // a value like "1rem:2rem; color:red" from a malformed extraction would
    // terminate the declaration early and inject rogue CSS. Colons are NOT
    // rejected: they legitimately appear inside url(data:...) and protocol
    // references.
    const hasBadChars = (s: string) =>
      s.includes("<") || s.includes(">") || s.includes("{") || s.includes("}") || s.includes(";");

    // 1. Raw CSS variables from extraction (highest priority — original names)
    if (cssVariables) {
      for (const [name, value] of Object.entries(cssVariables)) {
        const varName = name.startsWith("--") ? name : `--${name}`;
        // Skip malformed names (e.g. "--size);width: var(--size)" from broken extraction)
        if (!validNameRe.test(varName)) continue;
        // Skip values that could break HTML/CSS parsing
        if (hasBadChars(value)) continue;
        vars.set(varName, value);
      }
    }

    // 2. Structured tokens with cssVariable set (fill gaps from Figma extractions)
    if (tokens) {
      const allTokens = [
        ...(tokens.colors ?? []),
        ...(tokens.typography ?? []),
        ...(tokens.spacing ?? []),
        ...(tokens.radius ?? []),
        ...(tokens.effects ?? []),
        ...(tokens.motion ?? []),
      ];
      for (const t of allTokens) {
        if (!t.cssVariable || !t.value) continue;
        const varName = t.cssVariable.startsWith("--") ? t.cssVariable : `--${t.cssVariable}`;
        if (!validNameRe.test(varName)) continue;
        if (hasBadChars(t.value)) continue;
        if (!vars.has(varName)) {
          vars.set(varName, t.value);
        }
      }
    }

    if (vars.size === 0) return "";

    const lines = Array.from(vars.entries())
      .map(([name, value]) => `  ${name}: ${value};`)
      .join("\n");
    // Wrap in @layer so variant-defined :root variables always take priority.
    // Unlayered CSS (from the variant's own <style>) beats @layer in the cascade.
    return `@layer design-tokens {\n  :root {\n${lines}\n  }\n}`;
  } catch {
    // Graceful fallback — previews render without design tokens rather than breaking
    return "";
  }
}

export interface BuildSrcdocOptions {
  inspectorScript?: string;
  variantId?: string;
  iconPacks?: string[];
  fonts?: FontDeclaration[];
  uploadedFonts?: UploadedFont[];
  cssTokenBlock?: string;
  /** Kit metadata exposed to the iframe as window.__KIT__. Used by the
   * uniform showcase template to render a brand-aware hero (logo + name
   * + description) AND to drive per-kit component styling via the
   * styleProfile sub-field. Bespoke showcases ignore this and embed
   * their own. */
  kit?: {
    name?: string;
    description?: string;
    logoUrl?: string;
    /** Claude-derived style profile. Schema in lib/types/kit-style-profile.ts.
     * Renderer falls back to its DEFAULT_STYLE_PROFILE when absent. */
    styleProfile?: unknown;
  };
}

export function buildSrcdoc(js: string, componentName: string, opts?: BuildSrcdocOptions): string;
/** @deprecated Use options object overload instead. */
export function buildSrcdoc(js: string, componentName: string, inspectorScript?: string, _variantId?: string, iconPacks?: string[]): string;
export function buildSrcdoc(
  js: string,
  componentName: string,
  inspectorScriptOrOpts?: string | BuildSrcdocOptions,
  _variantId?: string,
  iconPacks?: string[]
): string {
  // Support both old positional args and new options object
  let opts: BuildSrcdocOptions;
  if (typeof inspectorScriptOrOpts === "object" && inspectorScriptOrOpts !== null) {
    opts = inspectorScriptOrOpts;
  } else {
    opts = {
      inspectorScript: inspectorScriptOrOpts ?? undefined,
      variantId: _variantId,
      iconPacks,
    };
  }
  // Embed transpiled JS as a JSON-encoded string literal. This safely handles
  // ALL special characters (quotes, backslashes, angle brackets, non-ASCII)
  // without base64/eval. Matches the proven approach used in TestPanel.
  //
  // The module code runs inside a dynamically created <script> element via
  // textContent (bypasses HTML parsing), with CJS shims prepended in the
  // SAME script so they share scope.
  const jsStr = JSON.stringify(js)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e");

  const { scriptTags: iconScriptTags, requireMappings: iconRequireMappings } = buildIconCdnScripts(opts.iconPacks);

  // Build font loading tags
  const fontResult = buildFontTags(opts.fonts, opts.uploadedFonts);
  const bodyFont = fontResult.primaryFamily
    ? `"${fontResult.primaryFamily}",system-ui,sans-serif`
    : "system-ui,sans-serif";

  // Kit metadata exposed to the iframe as window.__KIT__. JSON-encoded so
  // any quotes / special chars survive HTML embedding intact.
  const kitJson = opts.kit
    ? JSON.stringify(opts.kit).replace(/</g, "\\u003c").replace(/>/g, "\\u003e")
    : null;

  return `<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<base href="${typeof globalThis.window !== 'undefined' ? globalThis.window.location.origin + '/' : '/'}">
${fontResult.linkTags}
<script src="https://cdn.tailwindcss.com"></${"script"}>
<script src="https://unpkg.com/react@18/umd/react.production.min.js"></${"script"}>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></${"script"}>
${iconScriptTags}
<style>${fontResult.fontFaceCSS ? fontResult.fontFaceCSS + "\n" : ""}body{margin:0;font-family:${bodyFont}}a[href]{cursor:default}</style>
${opts.cssTokenBlock ? `<style>${opts.cssTokenBlock}</style>` : ""}
${kitJson ? `<script>window.__KIT__=${kitJson};</${"script"}>` : ""}
</head><body>
<div id="root"></div>
<script>
function showError(msg){
  var el=document.createElement('pre');
  el.style.cssText='color:red;padding:16px;font-size:12px;white-space:pre-wrap';
  el.textContent=String(msg);
  document.getElementById('root').appendChild(el);
  window.parent.postMessage({type:'layout-preview-error',error:String(msg)},'*');
}
window.onerror=function(msg,src,line,col,err){
  if(err&&err.name==='SecurityError')return true;
  if(typeof src==='string'&&src.indexOf('extension')!==-1)return true;
  if(typeof msg==='string'&&msg.indexOf('SecurityError')!==-1)return true;
  showError(err?err.stack||err.message:msg);
  return true;
};
window.addEventListener('load',function(){
  try{
    var moduleCode=${jsStr};
    var s=document.createElement('script');
    s.textContent=[
      'var {useState,useEffect,useRef,useCallback,useMemo,useContext,useReducer,useId,useLayoutEffect,createContext,forwardRef,memo,Fragment,Children,cloneElement,isValidElement,lazy,Suspense,startTransition,useTransition,useDeferredValue}=React;',
      'var _exp={};',
      'var _motionProxy=new Proxy({},{get:function(_,tag){return function(props){return React.createElement(tag,props)}}});',
      'var _framerShim={motion:_motionProxy,AnimatePresence:function(p){return React.createElement(React.Fragment,null,p.children)}};',
      'var _iconStub=function(p){return React.createElement("svg",Object.assign({xmlns:"http://www.w3.org/2000/svg",width:p&&p.size||24,height:p&&p.size||24,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:2,strokeLinecap:"round",strokeLinejoin:"round"},p))};',
      'var _lucideShim=new Proxy({},{get:function(){return _iconStub}});',
      'var require=function(n){return ${iconRequireMappings}n==="react"?React:n==="react-dom"?ReactDOM:n==="react-dom/client"?ReactDOM:n==="framer-motion"?_framerShim:n==="lucide-react"?_lucideShim:{};};',
      'var exports=_exp,module={exports:_exp};',
      moduleCode,
      '(function(){',
      '  var C=_exp["default"]||_exp["${componentName}"]||_exp;',
      '  if(typeof C==="object"&&C.default)C=C.default;',
      '  if(typeof C!=="function"&&!(typeof C==="object"&&C)){showError("Component not found in module exports");return;}',
      '  ReactDOM.createRoot(document.getElementById("root")).render(React.createElement(C));',
      '  document.addEventListener("click",function(e){var t=e.target;while(t&&t.tagName!=="A")t=t.parentElement;if(t)e.preventDefault();},true);',
      '})();'
    ].join('\\n');
    document.body.appendChild(s);
  }catch(e){
    showError(e.stack||e.message);
  }
});
</${"script"}>
${opts.inspectorScript ? `<${"script"}>${opts.inspectorScript}</${"script"}>` : ""}
</body></html>`;
}
