-- 051_kit_hero_image.sql
--
-- Adds a second preview column so each kit can optionally carry a stylised
-- "hero cover" image generated by GPT Image 2 alongside the existing
-- Playwright screenshot. Card thumbnails prefer hero_image_url, falling back
-- to preview_image_url, falling back to the gradient placeholder.
--
-- Two columns, two independent jobs, two independent regen buttons.

ALTER TABLE layout_public_kit
  ADD COLUMN IF NOT EXISTS hero_image_url    TEXT,
  ADD COLUMN IF NOT EXISTS hero_generated_at TIMESTAMPTZ;

INSERT INTO layout_migrations (name)
VALUES ('051_kit_hero_image.sql')
ON CONFLICT (name) DO NOTHING;
