import { createAuthClient } from "better-auth/react";

export const authClient = createAuthClient({
  baseURL:
    typeof window !== "undefined"
      ? window.location.origin
      : process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
});

export const { signIn, signUp, signOut, useSession } = authClient;

// Password reset methods are dynamically generated by Better Auth
// based on server config (sendResetPassword). Cast to access them.
const client = authClient as unknown as {
  forgetPassword: (opts: { email: string; redirectTo: string }) => Promise<{ error: { message: string } | null }>;
  resetPassword: (opts: { newPassword: string; token: string }) => Promise<{ error: { message: string } | null }>;
};
export const forgetPassword = client.forgetPassword;
export const resetPassword = client.resetPassword;
