/**
 * Process image placeholders in generated TSX/HTML code.
 *
 * Calls the /api/generate/image batch endpoint to replace
 * data-generate-image attributes with real AI-generated image URLs.
 *
 * This module runs CLIENT-SIDE — no server-only imports allowed.
 */

import { getStoredGoogleApiKey } from "@/lib/hooks/use-api-key";

const IMAGE_PLACEHOLDER_RE = /data-generate-image=["'][^"']+["']/i;
const PLACEHOLDER_URL_DOMAINS = "placehold\\.co|via\\.placeholder\\.com|placeholder\\.com|images\\.unsplash\\.com|source\\.unsplash\\.com|picsum\\.photos|dummyimage\\.com|lorempixel\\.com|loremflickr\\.com|fakeimg\\.pl|placekitten\\.com|placebear\\.com|(?:i\\.)?pravatar\\.cc|randomuser\\.me|robohash\\.org|ui-avatars\\.com";
const PLACEHOLDER_URL_RE = new RegExp(`src=["'](?:https?:)?//(?:${PLACEHOLDER_URL_DOMAINS})`, "i");
const PLACEHOLDER_URL_RE_GLOBAL = new RegExp(`src=["'](?:https?:)?//(?:${PLACEHOLDER_URL_DOMAINS})`, "gi");
// Relative paths like src="/avatars/alex.jpg" are fake paths generated by AI
const RELATIVE_SRC_RE = /\bsrc=["']\/[^"'\s>]+["']/i;
const RELATIVE_SRC_RE_GLOBAL = /\bsrc=["']\/[^"'\s>]+["']/gi;

interface ProcessOptions {
  orgId?: string;
  brandColours?: string[];
  brandStyle?: string;
  /** Force regeneration even for images that already have real URLs */
  forceRegenerate?: boolean;
}

export interface ProcessCodeImagesResult {
  code: string;
  /** Whether images were skipped because no Google AI API key is configured */
  skippedNoKey: boolean;
  /** Number of images found as placeholders */
  placeholderCount: number;
  /** Number of images that failed to generate */
  failedCount: number;
  /** Specific error messages (e.g. safety policy blocks) */
  errors: string[];
}

/**
 * Check if code contains image placeholders and process them via the API.
 * Returns the updated code plus status information about what happened.
 */
export async function processCodeImages(
  code: string,
  options: ProcessOptions = {}
): Promise<ProcessCodeImagesResult> {
  const hasPlaceholders = IMAGE_PLACEHOLDER_RE.test(code) || PLACEHOLDER_URL_RE.test(code) || RELATIVE_SRC_RE.test(code);
  if (!hasPlaceholders) return { code, skippedNoKey: false, placeholderCount: 0, failedCount: 0, errors: [] };

  // Count placeholders for reporting
  const dataAttrCount = (code.match(/data-generate-image=["'][^"']+["']/gi) ?? []).length;
  const urlCount = (code.match(PLACEHOLDER_URL_RE_GLOBAL) ?? []).length;
  const relativeCount = (code.match(RELATIVE_SRC_RE_GLOBAL) ?? []).length;
  const placeholderCount = dataAttrCount + urlCount + relativeCount;

  try {
    const headers: Record<string, string> = { "Content-Type": "application/json" };
    const googleKey = getStoredGoogleApiKey();
    if (googleKey) headers["X-Google-Api-Key"] = googleKey;

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 120_000);

    let res: Response;
    try {
      res = await fetch("/api/generate/image", {
        method: "POST",
        credentials: "include",
        headers,
        body: JSON.stringify({
          mode: "batch",
          html: code,
          orgId: options.orgId,
          brandColours: options.brandColours,
          brandStyle: options.brandStyle,
          forceRegenerate: options.forceRegenerate,
        }),
        signal: controller.signal,
      });
    } finally {
      clearTimeout(timeout);
    }

    if (!res.ok) {
      const errBody = await res.json().catch(() => ({ error: "Unknown error" }));

      if (errBody.code === "NO_API_KEY") {
        return { code, skippedNoKey: true, placeholderCount, failedCount: 0, errors: [] };
      }

      const apiErr = errBody.error ?? `HTTP ${res.status}`;
      console.warn(`[process-code-images] API error: ${apiErr}`);
      return { code, skippedNoKey: false, placeholderCount, failedCount: placeholderCount, errors: [apiErr] };
    }

    const data = await res.json();

    if (data.failedCount > 0) {
      console.warn(
        `[process-code-images] ${data.failedCount}/${data.totalCount} images failed to generate`,
        data.errors?.[0] ?? ""
      );
    }

    return {
      code: data.html ?? code,
      skippedNoKey: false,
      placeholderCount: data.totalCount ?? placeholderCount,
      failedCount: data.failedCount ?? 0,
      errors: (data.errors as string[]) ?? [],
    };
  } catch (err) {
    console.warn("[process-code-images] Failed:", err);
    const errMsg = err instanceof Error ? err.message : "Image processing failed";
    return { code, skippedNoKey: false, placeholderCount, failedCount: placeholderCount, errors: [errMsg] };
  }
}
