/**
 * Process image placeholders in generated TSX/HTML code.
 *
 * Calls the /api/generate/image batch endpoint to replace
 * data-generate-image attributes with real AI-generated image URLs.
 *
 * This module runs CLIENT-SIDE — no server-only imports allowed.
 */

import { getStoredGoogleApiKey } from "@/lib/hooks/use-api-key";

// Matches both literal strings and JSX expressions: data-generate-image="..." or data-generate-image={...}
const IMAGE_PLACEHOLDER_RE = /data-generate-image=(?:["'][^"']+["']|\{[^}]+\})/i;
const PLACEHOLDER_URL_DOMAINS = "placehold\\.co|via\\.placeholder\\.com|placeholder\\.com|images\\.unsplash\\.com|source\\.unsplash\\.com|picsum\\.photos|dummyimage\\.com|lorempixel\\.com|loremflickr\\.com|fakeimg\\.pl|placekitten\\.com|placebear\\.com|(?:i\\.)?pravatar\\.cc|randomuser\\.me|robohash\\.org|ui-avatars\\.com";
const PLACEHOLDER_URL_RE = new RegExp(`src=["'](?:https?:)?//(?:${PLACEHOLDER_URL_DOMAINS})`, "i");
const PLACEHOLDER_URL_RE_GLOBAL = new RegExp(`src=["'](?:https?:)?//(?:${PLACEHOLDER_URL_DOMAINS})`, "gi");
// Relative paths like src="/avatars/alex.jpg" are fake paths generated by AI
const RELATIVE_SRC_RE = /\bsrc=["']\/[^"'\s>]+["']/i;
const RELATIVE_SRC_RE_GLOBAL = /\bsrc=["']\/[^"'\s>]+["']/gi;
// Avatar divs: <div className="...rounded-full...">Matt</div> (server-side converter handles these)
const AVATAR_DIV_RE = /<(?:div|span)\s[^>]*className=["'][^"']*rounded-full[^"']*["'][^>]*>[^<]{1,5}<\/(?:div|span)>/i;
// Corrupted URLs from double-prefix bug or bare filenames without path
const CORRUPTED_URL_RE = /src=["'](?:https?:\/\/[^"']*?https?:\/\/[^"']*\/api\/storage\/|(?!data:|https?:|\/)[\w-]+\.(?:jpg|jpeg|png|webp|gif)["'])/i;

interface ProcessOptions {
  orgId?: string;
  brandColours?: string[];
  brandStyle?: string;
  /** Force regeneration even for images that already have real URLs */
  forceRegenerate?: boolean;
  /** AbortSignal for cancellation */
  signal?: AbortSignal;
  /** Progress callback: called with (completed, total) as each image finishes */
  onProgress?: (completed: number, total: number) => void;
}

export interface ProcessCodeImagesResult {
  code: string;
  /** Whether images were skipped because no Google AI API key is configured */
  skippedNoKey: boolean;
  /** Number of images found as placeholders */
  placeholderCount: number;
  /** Number of images that failed to generate */
  failedCount: number;
  /** Specific error messages (e.g. safety policy blocks) */
  errors: string[];
}

/**
 * Check if code contains image placeholders and process them via the API.
 * Returns the updated code plus status information about what happened.
 */
export async function processCodeImages(
  code: string,
  options: ProcessOptions = {}
): Promise<ProcessCodeImagesResult> {
  const hasPlaceholders = IMAGE_PLACEHOLDER_RE.test(code) || PLACEHOLDER_URL_RE.test(code) || RELATIVE_SRC_RE.test(code) || AVATAR_DIV_RE.test(code) || CORRUPTED_URL_RE.test(code);
  if (!hasPlaceholders) return { code, skippedNoKey: false, placeholderCount: 0, failedCount: 0, errors: [] };

  // Count placeholders for reporting
  const dataAttrCount = (code.match(/data-generate-image=(?:["'][^"']+["']|\{[^}]+\})/gi) ?? []).length;
  const urlCount = (code.match(PLACEHOLDER_URL_RE_GLOBAL) ?? []).length;
  const relativeCount = (code.match(RELATIVE_SRC_RE_GLOBAL) ?? []).length;
  const placeholderCount = dataAttrCount + urlCount + relativeCount;

  try {
    const headers: Record<string, string> = { "Content-Type": "application/json" };
    const googleKey = getStoredGoogleApiKey();
    if (googleKey) headers["X-Google-Api-Key"] = googleKey;

    // Use caller's signal if provided, otherwise create our own with 5-minute timeout
    const externalSignal = options.signal;
    const timeoutController = new AbortController();
    const timeout = setTimeout(() => timeoutController.abort(), 300_000);

    // Combine caller signal + timeout signal
    const combinedSignal = externalSignal
      ? combineSignals(externalSignal, timeoutController.signal)
      : timeoutController.signal;

    let res: Response;
    try {
      res = await fetch("/api/generate/image", {
        method: "POST",
        credentials: "include",
        headers,
        body: JSON.stringify({
          mode: "batch",
          html: code,
          orgId: options.orgId,
          brandColours: options.brandColours,
          brandStyle: options.brandStyle,
          forceRegenerate: options.forceRegenerate,
        }),
        signal: combinedSignal,
      });
    } finally {
      clearTimeout(timeout);
    }

    if (!res.ok) {
      const errBody = await res.json().catch(() => ({ error: "Unknown error" }));

      if (errBody.code === "NO_API_KEY") {
        return { code, skippedNoKey: true, placeholderCount, failedCount: 0, errors: [] };
      }

      const apiErr = errBody.error ?? `HTTP ${res.status}`;
      console.warn(`[process-code-images] API error: ${apiErr}`);
      return { code, skippedNoKey: false, placeholderCount, failedCount: placeholderCount, errors: [apiErr] };
    }

    // Check if the response is SSE (streaming) or JSON
    const contentType = res.headers.get("content-type") ?? "";

    if (contentType.includes("text/event-stream")) {
      // SSE streaming: parse events for progressive updates
      return await consumeSSEStream(res, code, placeholderCount, options.onProgress);
    }

    // Fallback: standard JSON response
    const data = await res.json();

    if (data.failedCount > 0) {
      console.warn(
        `[process-code-images] ${data.failedCount}/${data.totalCount} images failed to generate`,
        data.errors?.[0] ?? ""
      );
    }

    // Report total count as progress if callback provided
    if (options.onProgress && data.totalCount) {
      options.onProgress(data.totalCount - (data.failedCount ?? 0), data.totalCount);
    }

    return {
      code: data.html ?? code,
      skippedNoKey: false,
      placeholderCount: data.totalCount ?? placeholderCount,
      failedCount: data.failedCount ?? 0,
      errors: (data.errors as string[]) ?? [],
    };
  } catch (err) {
    if ((err as Error).name === "AbortError") {
      throw err; // Let the caller handle abort
    }
    console.warn("[process-code-images] Failed:", err);
    const errMsg = err instanceof Error ? err.message : "Image processing failed";
    return { code, skippedNoKey: false, placeholderCount, failedCount: placeholderCount, errors: [errMsg] };
  }
}

// ---------------------------------------------------------------------------
// SSE stream consumer
// ---------------------------------------------------------------------------

async function consumeSSEStream(
  res: Response,
  originalCode: string,
  placeholderCount: number,
  onProgress?: (completed: number, total: number) => void,
): Promise<ProcessCodeImagesResult> {
  const reader = res.body?.getReader();
  if (!reader) {
    return { code: originalCode, skippedNoKey: false, placeholderCount, failedCount: placeholderCount, errors: ["No response body"] };
  }

  const decoder = new TextDecoder();
  let buffer = "";
  let latestHtml = originalCode;
  let totalCount = placeholderCount;
  let failedCount = 0;
  let completed = 0;
  const errors: string[] = [];

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });

    // Parse SSE events from buffer
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? ""; // Keep incomplete line in buffer

    for (const line of lines) {
      if (!line.startsWith("data: ")) continue;
      const jsonStr = line.slice(6).trim();
      if (!jsonStr) continue;

      try {
        const event = JSON.parse(jsonStr);

        if (event.type === "progress") {
          completed++;
          totalCount = event.total ?? totalCount;
          onProgress?.(completed, totalCount);
        } else if (event.type === "error") {
          failedCount++;
          if (event.message) errors.push(event.message);
          onProgress?.(completed, totalCount);
        } else if (event.type === "complete") {
          latestHtml = event.html ?? latestHtml;
          totalCount = event.totalCount ?? totalCount;
          failedCount = event.failedCount ?? failedCount;
          if (event.errors) errors.push(...event.errors);
        }
      } catch {
        // Skip malformed SSE events
      }
    }
  }

  return {
    code: latestHtml,
    skippedNoKey: false,
    placeholderCount: totalCount,
    failedCount,
    errors,
  };
}

// ---------------------------------------------------------------------------
// Signal combiner
// ---------------------------------------------------------------------------

function combineSignals(...signals: AbortSignal[]): AbortSignal {
  const controller = new AbortController();
  for (const signal of signals) {
    if (signal.aborted) {
      controller.abort(signal.reason);
      return controller.signal;
    }
    signal.addEventListener("abort", () => controller.abort(signal.reason), { once: true });
  }
  return controller.signal;
}
